# Generated by Django 2.2.5 on 2019-11-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('barcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='barcode')),
                ('acc_no', models.CharField(blank=True, max_length=10, null=True, verbose_name='barcode')),
                ('pub_year', models.CharField(blank=True, max_length=10, null=True, verbose_name='barcode')),
                ('price', models.FloatField(blank=True, verbose_name='price')),
            ],
        ),
    ]
