# Generated by Django 2.2.5 on 2019-11-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('barcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='barcode')),
                ('acc_no', models.CharField(blank=True, max_length=10, null=True, verbose_name='accession number')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='title')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='author')),
                ('loc', models.CharField(blank=True, max_length=10, null=True, verbose_name='location code')),
                ('classification', models.CharField(blank=True, max_length=10, null=True, verbose_name='classification')),
                ('price', models.FloatField(blank=True, verbose_name='price')),
                ('pub_year', models.CharField(blank=True, max_length=10, null=True, verbose_name='publication year')),
            ],
        ),
    ]
