# Generated by Django 2.2.5 on 2020-01-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='edited',
            field=models.BooleanField(default=True, verbose_name='Edited'),
        ),
    ]
