# Generated by Django 2.2.5 on 2019-11-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_no',
            field=models.IntegerField(default=0, verbose_name='group_no'),
            preserve_default=False,
        ),
    ]
