# Generated by Django 2.2.5 on 2019-12-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='shelf_no',
            field=models.CharField(default=0, max_length=20, verbose_name='shelf no'),
            preserve_default=False,
        ),
    ]
