# Generated by Django 2.2.5 on 2019-12-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_stockentry_shelf_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
