# Generated by Django 2.2.5 on 2019-11-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191106_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('barcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='barcode')),
                ('status', models.CharField(choices=[('D', 'Duplicate'), ('O', 'Other'), ('M', 'Missmatch')], max_length=1, verbose_name='status')),
            ],
        ),
    ]
