# Generated by Django 2.2.5 on 2019-11-18 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_stockentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='remarks',
            field=models.TextField(null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='barcode',
            field=models.CharField(max_length=10, verbose_name='barcode'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='status',
            field=models.CharField(choices=[('D', 'Duplicate'), ('O', 'Other'), ('M', 'Missmatch')], max_length=1, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='user',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
